apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  labels:
    app: registry-svc
    version: v9
spec:
  selector:
    app: registry
    version: v9
  type: ClusterIP
  clusterIP: 10.1.129.1
  ports:
    - name: registry-port
      port: 5000
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: registry
  labels:
    app: registry
    version: v9
spec:
  replicas: 1
  selector:
    app: registry
    version: v9
  template:
    metadata:
      labels:
        app: registry
        version: v9
    spec:
      containers:
        - name: registry
          image: bhuisgen/alpine-registry
          ports:
            - containerPort: 5000
              name: registry-port
              protocol: TCP